init:
  - echo %PATH%

environment:
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: larskanis
    BINTRAY_REPOSITORY: rubyinstaller2-packages
    BINTRAY_VERSION: latest
    PACMAN_REPOSITORY_NAME: ci.ri2
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)
    GPGPASSWD:
        secure: /DELcKSZC+R4HdXgsqR1RtC+IrDZ3Xut/vzV/KgepE3M8OsjJtmWutN0+Jvc2Iv2
    BINTRAY_API_KEY:
        secure: yaAnKXWjX6uB9WwCZ4ZQm/R0bCvyribyGYEoTu/kw+F6v8CgJ26n8+u9C6cnuBIN

build_script:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

artifacts:
    - path: artifacts\*

deploy:
    - provider: BinTray
      username: $(BINTRAY_ACCOUNT)
      subject: $(BINTRAY_ACCOUNT)
      repo: $(BINTRAY_REPOSITORY)
      package: $(PACMAN_REPOSITORY_NAME)
      version: latest
      publish: true
      override: true
      api_key: $(BINTRAY_API_KEY)

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
